# Generated by Django 6.0.2 on 2026-03-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_mode', models.CharField(choices=[('Practice Mode', 'Practice Mode'), ('Assessment Mode', 'Timed Assesment'), ('Full Developer Mock', 'Full Developer Mock')], max_length=50)),
                ('category', models.CharField(choices=[('Logical Reasoning', 'Logical Reasoning'), ('Programming Logic', 'Programming Logic'), ('CS Fundamentals', 'Cs Fundamentals'), ('Core Concepts', 'Core Concepts'), ('Data Interpretation', 'Data Interpretation'), ('All Categories', 'All Categories')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('no_of_questions', models.IntegerField(default=0)),
                ('no_of_attempts', models.IntegerField(default=0)),
                ('no_of_correct_answers', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AptitudeQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Logical Reasoning', 'Logical Reasoning'), ('Programming Logic', 'Programming Logic'), ('CS Fundamentals', 'Cs Fundamentals'), ('Core Concepts', 'Core Concepts'), ('Data Interpretation', 'Data Interpretation'), ('All Categories', 'All Categories')], max_length=50)),
                ('question_text', models.JSONField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('correct_answer', models.JSONField()),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='aptitude.aptitudetest')),
            ],
        ),
    ]
