# Generated by Django 6.0.2 on 2026-03-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('company', models.CharField(choices=[('Startup', 'Startup'), ('Mid-size', 'Mid Size'), ('FAANG', 'Faang'), ('Fortune 500', 'Fortune500'), ('Consulting Firm', 'Consulting'), ('DevOps Engineer', 'Devops')], max_length=100)),
                ('experience_level', models.CharField(choices=[('0-1 years', 'Zero To One'), ('1-3 years', 'One To Three'), ('3-5 years', 'Three To Five'), ('5+ years', 'Five Plus')], max_length=50)),
                ('tech_stack', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer_text', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview_prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.interviewprep')),
            ],
        ),
    ]
